import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import Footer from "@/components/footer/Footer";

import "../globals.css";
import { string, unknown } from "zod";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amebo Login",
  description: "Generated by create next app",
};

interface Styles {
  body: string;
  content: string;
}

const styles: Styles = {
  body: "min-h-screen flex flex-col bg-dark-1", // Ensure the body takes at least the full height of the viewport
  content: "flex-1", // Allow the content to take up the remaining vertical space
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang='en'>
        <body className={`${inter.className} ${styles.body}`}>
          <div className={styles.content}>
            {children}
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
